In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import scipy
import sklearn
from math import *
from prettytable import PrettyTable
from functools import partial
from decimal import Decimal

plt.rcParams['font.sans-serif'] = ['Microsoft YaHei']  # 黑体
plt.rcParams['axes.unicode_minus'] = False  # 解决无法显示符号的问题
palette = 'deep'
sns.set(font='Microsoft YaHei', font_scale=1.2,
        palette=palette)  # 解决Seaborn中文显示问题

In [2]:
alpha = 1.5
theta = 120
海域中心点深度 = 120


def nm2m(海里):
    return 海里 * 1852

In [3]:
def gamma(beta):
    val = asin(abs(sin(radians(alpha) * sin(radians(beta)))))
    return val


def deep(测量船距离中心点, beta):
    val = 海域中心点深度 + (测量船距离中心点 *
                     (cos(radians(beta)) * sin(radians(alpha)))) \
        / sqrt(1 - cos(radians(beta)) ** 2 * sin(radians(alpha)) ** 2)
                    #  abs(cos(radians(beta)) * sin(radians(alpha)))) \
    return val


def 覆盖宽度(测量船距离中心点, 测线夹角):
    beta = 测线夹角
    gammar = gamma(beta)
    val = deep(测量船距离中心点, beta) \
        * cos(radians(gammar)) * sin(radians(theta)) \
        / (cos(radians(gammar - theta / 2)) * cos(radians(gammar + theta / 2)))
    return val

In [4]:
row_index = [i * 45 for i in range(8)]
columes = [i * Decimal('0.3') for i in range(8)]

row_index = list(map(str, row_index))
columes = list(map(str, columes))

In [5]:
df = pd.DataFrame(columns=columes, index=row_index)

In [6]:
for rowIdx in range(len(df)):
    for colIdx in range(len(df.columns)):
        测量船距离中心点 = float(df.columns[colIdx])
        测线夹角 = float(df.index[rowIdx])
        df.iloc[rowIdx, colIdx] = 覆盖宽度(nm2m(测量船距离中心点), 测线夹角)

df

,0.0,0.3,0.6,0.9,1.2,1.5,1.8,2.1
0,415.692194,466.091055,516.489916,566.888777,617.287638,667.6865,718.085361,768.484222
45,415.692346,451.323628,486.95491,522.586191,558.217473,593.848755,629.480037,665.111319
90,415.692498,415.692498,415.692498,415.692498,415.692498,415.692498,415.692498,415.692498
135,415.692346,380.061064,344.429782,308.7985,273.167218,237.535936,201.904654,166.273372
180,415.692194,365.293333,314.894472,264.49561,214.096749,163.697888,113.299027,62.900166
225,415.692346,380.061064,344.429782,308.7985,273.167218,237.535936,201.904654,166.273372
270,415.692498,415.692498,415.692498,415.692498,415.692498,415.692498,415.692498,415.692498
315,415.692346,451.323628,486.95491,522.586191,558.217473,593.848755,629.480037,665.111319

In [7]:
df.to_excel('第二问ans.xlsx')